/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class image_desktop_Zic */

#ifndef _Included_image_desktop_Zic
#define _Included_image_desktop_Zic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     image_desktop_Zic
 * Method:    createImagePtrNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_image_desktop_Zic_createImagePtrNative
  (JNIEnv *, jobject);

/*
 * Class:     image_desktop_Zic
 * Method:    destroyImagePtrNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_image_desktop_Zic_destroyImagePtrNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     image_desktop_Zic
 * Method:    loadImageNative
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_image_desktop_Zic_loadImageNative
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     image_desktop_Zic
 * Method:    cloneNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_image_desktop_Zic_cloneNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     image_desktop_Zic
 * Method:    getImageWidthNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_image_desktop_Zic_getImageWidthNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     image_desktop_Zic
 * Method:    getImageHeightNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_image_desktop_Zic_getImageHeightNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     image_desktop_Zic
 * Method:    getDepthNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_image_desktop_Zic_getDepthNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     image_desktop_Zic
 * Method:    getColorSpaceNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_image_desktop_Zic_getColorSpaceNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     image_desktop_Zic
 * Method:    saveNative
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_image_desktop_Zic_saveNative
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     image_desktop_Zic
 * Method:    saveToNative
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_image_desktop_Zic_saveToNative
  (JNIEnv *, jobject, jlong, jstring, jlong);

/*
 * Class:     image_desktop_Zic
 * Method:    contrastNative
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_image_desktop_Zic_contrastNative
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     image_desktop_Zic
 * Method:    cropNative
 * Signature: (JJJJJ)V
 */
JNIEXPORT void JNICALL Java_image_desktop_Zic_cropNative
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     image_desktop_Zic
 * Method:    exposureNative
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_image_desktop_Zic_exposureNative
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     image_desktop_Zic
 * Method:    gammaNative
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_image_desktop_Zic_gammaNative
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     image_desktop_Zic
 * Method:    bilateralFilterNative
 * Signature: (JIFF)V
 */
JNIEXPORT void JNICALL Java_image_desktop_Zic_bilateralFilterNative
  (JNIEnv *, jobject, jlong, jint, jfloat, jfloat);

/*
 * Class:     image_desktop_Zic
 * Method:    allocByteMemoryNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_image_desktop_Zic_allocByteMemoryNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     image_desktop_Zic
 * Method:    resizeByteMemoryNative
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_image_desktop_Zic_resizeByteMemoryNative
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     image_desktop_Zic
 * Method:    freeByteMemoryNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_image_desktop_Zic_freeByteMemoryNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     image_desktop_Zic
 * Method:    getImageOutBufferSizeNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_image_desktop_Zic_getImageOutBufferSizeNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     image_desktop_Zic
 * Method:    writeToBufferNative
 * Signature: (JJJ[B)V
 */
JNIEXPORT void JNICALL Java_image_desktop_Zic_writeToBufferNative
  (JNIEnv *, jobject, jlong, jlong, jlong, jbyteArray);

/*
 * Class:     image_desktop_Zic
 * Method:    convertColorSpaceNative
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_image_desktop_Zic_convertColorSpaceNative
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     image_desktop_Zic
 * Method:    convertDepthNative
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_image_desktop_Zic_convertDepthNative
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     image_desktop_Zic
 * Method:    brightenNative
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_image_desktop_Zic_brightenNative
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     image_desktop_Zic
 * Method:    sobelNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_image_desktop_Zic_sobelNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     image_desktop_Zic
 * Method:    scharrNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_image_desktop_Zic_scharrNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     image_desktop_Zic
 * Method:    stretchContrastNative
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_image_desktop_Zic_stretchContrastNative
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     image_desktop_Zic
 * Method:    flipNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_image_desktop_Zic_flipNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     image_desktop_Zic
 * Method:    verticalFlipNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_image_desktop_Zic_verticalFlipNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     image_desktop_Zic
 * Method:    flopNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_image_desktop_Zic_flopNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     image_desktop_Zic
 * Method:    transposeNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_image_desktop_Zic_transposeNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     image_desktop_Zic
 * Method:    histogramNative
 * Signature: (JLjava/util/Map;)V
 */
JNIEXPORT void JNICALL Java_image_desktop_Zic_histogramNative
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     image_desktop_Zic
 * Method:    exifMetadataNative
 * Signature: (JLjava/util/Map;)V
 */
JNIEXPORT void JNICALL Java_image_desktop_Zic_exifMetadataNative
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     image_desktop_Zic
 * Method:    boxBlurNative
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_image_desktop_Zic_boxBlurNative
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     image_desktop_Zic
 * Method:    gaussianBlurNative
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_image_desktop_Zic_gaussianBlurNative
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     image_desktop_Zic
 * Method:    hslAdjustNative
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_image_desktop_Zic_hslAdjustNative
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     image_desktop_Zic
 * Method:    medianBlurNative
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_image_desktop_Zic_medianBlurNative
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     image_desktop_Zic
 * Method:    writeToNioBufferNative
 * Signature: (JLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_image_desktop_Zic_writeToNioBufferNative
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
